name: Merge JSON Build

on:
  push:
    branches: [ "main" ]  # mainブランチにpushされたら実行
  workflow_dispatch:      # 手動実行ボタンも出せるようにする

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Merge Script
        run: python main.py

      - name: Upload Combined JSON
        uses: actions/upload-artifact@v4
        with:
          name: combined-json-data
          path: combined.json
